# Generated by Django 3.2.7 on 2021-09-23 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('item', '0001_initial'),
        ('comanda_cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('status', models.CharField(max_length=10)),
                ('id_comanda', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='comanda_cliente.comandacliente')),
                ('id_item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='item.item')),
            ],
        ),
    ]
