# Generated by Django 3.2.7 on 2021-09-29 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(default='Aberto', max_length=10),
        ),
    ]
